// Configurações de Tema, Cores e Fontes do Tailwind CSS
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e1",
        background: "#f8faf8",
        "on-tertiary-fixed-variant": "#24502c",
        "on-surface-variant": "#42493e",
        "tertiary-fixed-dim": "#a2d3a4",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d9e6da",
        tertiary: "#15411f",
        "on-tertiary-container": "#9ecea0",
        "primary-fixed": "#bcf0ae",
        "surface-variant": "#e1e3e1",
        error: "#ba1a1a",
        "surface-bright": "#f8faf8",
        "on-background": "#191c1b",
        "primary-container": "#2d5a27",
        "secondary-fixed-dim": "#bdcabe",
        "inverse-surface": "#2e3130",
        "on-secondary-fixed": "#131e17",
        "surface-container": "#eceeec",
        "on-primary-container": "#9dd090",
        "on-error-container": "#93000a",
        "secondary-container": "#d9e6da",
        "on-surface": "#191c1b",
        "tertiary-container": "#2d5934",
        surface: "#f8faf8",
        "primary-fixed-dim": "#a1d494",
        primary: "#154212",
        "surface-container-low": "#f2f4f2",
        "on-primary-fixed-variant": "#23501e",
        outline: "#72796e",
        "on-tertiary-fixed": "#002109",
        "inverse-on-surface": "#eff1ef",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#5b675e",
        "on-primary": "#ffffff",
        "surface-tint": "#3b6934",
        "on-error": "#ffffff",
        "inverse-primary": "#a1d494",
        "tertiary-fixed": "#bdefbe",
        secondary: "#556158",
        "outline-variant": "#c2c9bb",
        "surface-container-high": "#e6e9e7",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3e4a41",
        "surface-dim": "#d8dad9",
        "on-primary-fixed": "#002201",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "16px",
        lg: "40px",
        xs: "4px",
        xl: "64px",
        base: "8px",
        sm: "12px",
        md: "24px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
};